<MyLayout>

    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height

        Label:
            id: name_label
            text: "C'est quoi ton nom"
            font_size: 32
        
        TextInput:
            id: name_input
            multiline: False
            size_hint: (1, 0.5)
        
        Button:
            size_hint:(1, 0.5)
            font_size: 32
            text: "Soumettre"
            on_press: root.press()