<MyLayout>

    BoxLayout:
        #orientation: "horizontal" # alignement horizontal des bouton
        orientation: "vertical"
        size: root.width, root.height
        
        #spacing: 20 # Mettre de l'espace entre les boutons
        #padding: 50 # Espace sur le bord

        Image:
            source: 'photo.jpg'
            allow_stretch: True # Etirer l'image
            keep_ratio:False # Refuser le ratio de l'image


        #Button:
        #    text:"Salut le monde"